### ISSUE TITLE
Saving and loading models from disk 

### ISSUE THREAD

**Issue by pravsels** [vanderschaarlab/synthcity#130]

**Comment by bcebere** [comment]
Hello @pravsels 

Thank you for your feedback.

[tutorial0_basic_examples](https://github.com/vanderschaarlab/synthcity/blob/main/tutorials/tutorial0_basic_examples.ipynb) includes a serialization example, to bytes.

You can use the functions from `synthcity.utils.serialization` to save to bytes or to files, and load the buffers.

We will update the docs to include the serialization details.
