### ISSUE TITLE
Add CONTRIBUTING.MD

### ISSUE THREAD

**Issue by bcebere** [vanderschaarlab/synthcity#146]
It should be clear for new contributors how to set their dev environment and how to run static checks locally before raising a PR.

This should also be added as a page at the top of README.md, for easy access.

The list should include:
 - creating a new conda/work env.
 - installing and running the pre-commit tools.
 - installing the dev depends using `pip install synthcity[testing]`
 - running the tests locally

Example from Opacus: https://github.com/pytorch/opacus/blob/main/CONTRIBUTING.md

**Comment by pravsels** [comment]
I would find this very useful. I'm using a docker container locally and changes I make to the synthcity repository don't seem to be recompiling. I'm having to do a `pip install .` every time. Same issue on Colab.

**Comment by bcebere** [comment]
Hello @pravsels 

You can use `pip install -e .` and you won't need to reinstall the library on every change. This installs the library in the editable mode.
