### ISSUE TITLE
Device inconsistency in denoising diffusion plugin

### ISSUE THREAD

**Issue by dionman** [vanderschaarlab/synthcity#160]
## Description
When initialising the DDPM plugin with with device set to cuda, there is an error occurring during training due to inconsistent devices across tensors. I think a mitigation should be added as in the following line https://github.com/dionman/synthcity/blob/0d7ebf5188f366e722b65faae8ccdebaf0a6054e/src/synthcity/plugins/core/models/tabular_ddpm/modules.py#L57

**Comment by pravsels** [comment]
PR #161 aims to address this.
