### ISSUE TITLE
I have some problems when using fflows for data generation

### ISSUE THREAD

**Issue by llllyqqqq** [vanderschaarlab/synthcity#164]
## Question
I have some problems when using fflows for data generation

## Further Information
I encountered some problems when using fflows for data generation. When I modified the data format at the beginning and imported it into the data loader, there would be some errors during the training process, but I solved it by increasing the data set, but later on. There are some problems when the data is generated, and now I don't know where the problem is.

## Screenshots
First of all, I encountered the following bug when I ran the program after modifying the data format.(ValueError: With n_samples=1, test_size=None and train_size=0.8, the resulting train set will be empty. Adjust any of the aforementioned parameters.)
![image](https://user-images.githubusercontent.com/129362450/228744781-7ce8036b-83fc-45fd-b976-26bb4c379a40.png)

Then I increased the data set to more than 12 (that is, repeatedly added my original data set) and this bug no longer appeared.The problem encountered later is that after continuing to run, the step of training the model can run normally, but the subsequent generation of data is not generated as quickly as expected, but lasts for a long time as shown in the figure below, and finally outputs such a bug.
![image](https://user-images.githubusercontent.com/129362450/228745583-4fb88c01-3527-4d21-9d30-9a139e9bef61.png)
![image](https://user-images.githubusercontent.com/129362450/228745602-52d7b9d6-70a2-4f0d-95be-f439956f7af8.png)
![image](https://user-images.githubusercontent.com/129362450/228745636-97297682-d7e4-4e0e-8db7-bd78c0815934.png)
![image](https://user-images.githubusercontent.com/129362450/228745668-f11b4dd7-f19b-4728-b73b-2913fe62586c.png)

I don't know where the problem is now. The following is my code .  Hope you can give me an answer.
m = scipy.io.loadmat("D:/Thesis23/YongqiLi/data/ceshi/110ST_Fault_001_A_#rpm=500#torque=0.mat")
#Convert dict format
df = pd.DataFrame(map(np.ravel, m.values()), index=m.keys()).T
#intercept specified length
vib_X = df['vib_X'][0:512]
vib_Y = df['vib_Y'][0:512]
vib_Z = df['vib_Z'][0:512]
time_vib = df['time_vib_X'][0:512]
id = [0,1,2,3,4,5,6,7,8,9,10,11]
static_data = pd.DataFrame(
    {
        "id":id,
        "outcome":np.random.normal(loc=5, scale=1, size=(12)),
    }
)
tem_data = pd.DataFrame(
    {
        "observation":time_vib,
        "temp_vib_X":vib_X,
        "temp_vib_Y":vib_Y,
        "temp_vib_Z":vib_Z,
    }
)
outcome_data = static_data[['outcome']]
static_data = static_data.drop(columns=['outcome'])
static_data.set_index("id", inplace=True)
observation_data = tem_data['observation']
tem_data = tem_data.drop(columns=['observation'])

observations, temporal_dataframes = ([] for i in range(2))
observation_data = observation_data.tolist()
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
observations.append(observation_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data)
temporal_dataframes.append(tem_data) 

loader = TimeSeriesDataLoader(
    temporal_data = temporal_dataframes,
    observation_times = observations,
    static_data = static_data,
    outcome = outcome_data,
)
#
syn_model = Plugins().get("fflows")

syn_model.fit(loader)
#
syn_model.generate(count=1)

## System Information
 - WINDOWS
 -  Version:10
 - Language Version: [ Python 3.8]

## Additional Context
Here is my input data format
![image](https://user-images.githubusercontent.com/129362450/228747335-ed572a23-62f7-4c64-b39f-8aa0d78cfb6a.png)
![image](https://user-images.githubusercontent.com/129362450/228747454-3eea91bf-4a1a-4883-908b-23d84faea5d4.png)

There is a lot of input data, here is just to show the format, it is only part of the input data of the above code, and I don’t know if the format is correct.

**Comment by robsdavis** [comment]
Hi [llllyqqqq](https://github.com/llllyqqqq),

Thanks for engaging with synthcity!
It is difficult to see the structure of your data in some of the screen shots above, but I am guessing that this will be the source of the issue. I find that it generates correctly if I substitute  your variables with arrays of random values, as below:

```
vib_X = np.random.uniform(size=512)
vib_Y = np.random.uniform(size=512)
vib_Z = np.random.uniform(size=512)
time_vib = np.random.uniform(size=512)
```
What does he output of loader.info() look like?
