### ISSUE TITLE
Using RadialGAN with datasets that have different columns

### ISSUE THREAD

**Issue by bwbelljr** [vanderschaarlab/synthcity#165]
## Question
How do I use RadialGAN when the datasets have different but overlapping sets of columns?

## Further Information
Currently, I concatenate the datasets into one dataset (e.g., using `pd.concat`). However, this produces null values in datasets that do not share columns. Should I fill the null values with 0 or do some imputation before feeding into thee RadialGAN plugin? The original RadialGAN paper mentions that the technique handles feature mismatch. But it is unclear how this is fed into the model. Any example is appreciated. The documentation for RadialGAN is a good start, but segmenting the Iris dataset into 2 pseudo domains doesn't demonstrate feature mismatch.

## System Information
 - OS: Linux (Amazon Linux 2)
 - OS Version: n/a
 - Language Version: Python 3.10
 - Package Manager Version: Conda

**Comment by robsdavis** [comment]
Hi @bwbelljr,
Thanks for engaging with Synthcity! The version of RadialGAN currently implemented does not accept feature mismatch implicitly, so you will need to perform some imputation first. I would recommend using [hyperimpute](https://github.com/vanderschaarlab/hyperimpute) for this. Thank you for your question though. We will consider adding an imputation step into the RadialGAN method for this use case in the future!

**Comment by robsdavis** [comment]
There is now a [tutorial](https://github.com/vanderschaarlab/synthcity/blob/main/tutorials/tutorial9_dealing_with_missing_data.ipynb) on how to impute data with HyperImpute, which may be useful for this issue.
