### ISSUE TITLE
Demonstration of using fit along with hyperparameter optimization

### ISSUE THREAD

**Issue by dionman** [vanderschaarlab/synthcity#166]
Is there a notebook demonstrating how to use the optuna hyperparameter optimization capabilities of the models as part of fitting?

**Comment by bcebere** [comment]
Hello @dionman 

Thank you for your question. It would be an interesting tutorial.

We will try a notebook this week with an Optuna example.

**Comment by TZTsai** [comment]
Hello, is there anyone working on this issue? If not, I will work on it.

**Comment by bcebere** [comment]
Hello @TZTsai 

Absolutely,  thank you for working on this.
Let us know if you need help.

Just a few guidelines:
 - For a dataset and a task, you need to define an objective in Optuna.
 - To that end, you need to "translate" the hyperparam_space from a plugin to the optuna Trial suggestions.
 - Finally, given a set of args, you construct and evaluate the plugin.
 - For the evaluation, a good metric could be the detection.mlp metric, which discriminates real data from synthetic data. In other words, you ask Optuna to give you the hyperparams which create the closest synthetic data to the real data. Of course, many other metrics can be relevant here, it is up to you.

**Comment by TZTsai** [comment]
Hello @bcebere 

I have finished the tutorial. In order to let Optuna sample from the `hyperparam_space`, I added a script `optuna_sample.py` under utils/. Please check them in the new pull request.

**Comment by dionman** [comment]
Does the current implementation of the plugins support HPO search algorithm that allow early pruning of unpromising trials, e.g. optuna's [SuccessiveHalvingPruner](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.SuccessiveHalvingPruner.html#optuna.pruners.SuccessiveHalvingPruner)

**Comment by TZTsai** [comment]
I don't think so. To support early pruning, a plugin must support arbitrary callbacks in each iteration of training. A custom callback then can be provided that reports intermediate performance scores and raises `optuna.TrialPruned()` so as to prune this trial. However, the `DDPM` plugin does support a list of callbacks during fitting and I also implemented the `Callback` class in "synthcity/utils/callbacks.py". If needed, I can implement a `PruneOptunaTrial` callback class for early pruning.

**Comment by robsdavis** [comment]
The tutorial created by @TZTsai is available [here](https://github.com/vanderschaarlab/synthcity/blob/main/tutorials/tutorial8_hyperparameter_optimization.ipynb), which closes this issue.

**Comment by dionman** [comment]
is optuna timeout working for this notebook?

**Comment by TZTsai** [comment]
Hi, sorry this does not support minibatching.

发件人: DM
发送时间: 2023年6月8日 14:27
收件人: vanderschaarlab/synthcity
抄送: Tianzhang Cai; Mention
主题: Re: [vanderschaarlab/synthcity] Demonstration of using fit along withhyperparameter optimization (Issue #166)

does the computation of the validation score in the tutorial support minibatching?

**Comment by TZTsai** [comment]
Hi, sorry the notebook does not include optuna timeout.

发件人: DM
发送时间: 2023年6月9日 19:00
收件人: vanderschaarlab/synthcity
抄送: Tianzhang Cai; Mention
主题: Re: [vanderschaarlab/synthcity] Demonstration of using fit along withhyperparameter optimization (Issue #166)

is optuna timeout working for this notebook?
