### ISSUE TITLE
Goggle does not pass the generate_constraints test

### ISSUE THREAD

**Issue by TZTsai** [vanderschaarlab/synthcity#176]
I tried increasing `n_iter` to 500, but it still failed to generate valid samples. If it has passed the tests in the main branch, maybe it is due to some changes I made.
![图片](https://user-images.githubusercontent.com/34415979/230611910-ef937b8e-802c-419c-9eec-5323bf76bbb3.png)

**Comment by bcebere** [comment]
Hello. 

The tests work fine on the main branch, without any changes.

**Comment by TZTsai** [comment]
I think it is because I made the change that `get_nonlin('softmax') == nn.Softmax()`, but previously it should be `GumbelSoftmax()`.
