### ISSUE TITLE
Which models, if any, support likelihood evaluation

### ISSUE THREAD

**Issue by fountaindive** [vanderschaarlab/synthcity#182]
## Question
Are there any models which support likelihood evaluation of a sample as well as the ability to generate synthetic data?

Thanks!

**Comment by robsdavis** [comment]
Hi @fountaindive,

Thanks for getting in touch with your question!

The aim of the Synthcity library is to provide an easy-to-use API to generate synthetic data, as such, this forms the sole focus for the implementations of the models included. Therefore if you are looking for downstream predictive models that can provide you with likelihood evaluation, synthcity is unlikely to be the best library for you use case. That said, synthcity does have some predictive models included in the library, for example those that are used to calculate metrics etc. These tend to be the more  classic models, such as simple MLPs or XGBoost. 

I hope that answers your question. Please feel free to explore the library and get back in touch with any more questions!

**Comment by fountaindive** [comment]
Hi @robsdavis,

Having a library like this to unify the huge variety of generative models is *really* amazing so thanks for this package. 

thanks, that answers my question :)

best wishes
