### ISSUE TITLE
Test failing in tutorials

### ISSUE THREAD

**Issue by robsdavis** [vanderschaarlab/synthcity#189]
## Description
The tutorials test fails with a traceback the suggests the lifelines module may be the issue.

## How to Reproduce
Run the automated tests.

## Screenshots
![image](https://user-images.githubusercontent.com/62107751/236149510-a99661c2-3088-4400-a100-293c45a0d9e1.png)

**Comment by DrShushen** [comment]
Try updating requirements like this, I think this may be the same bug:
https://github.com/vanderschaarlab/temporai/blob/main/setup.cfg#L67-L68

**Comment by robsdavis** [comment]
Thanks @DrShushen, I was just looking at the same thing
