### ISSUE TITLE
Suspected coding mistake in PerformanceEvaluator

### ISSUE THREAD

**Issue by prabaey** [vanderschaarlab/synthcity#202]
## Description
There seems to be a coding mistake in the function `_evaluate_performance_regression` within the class `PerformanceEvaluator`. I think I spotted a typo in the transformation of the training and test set to numpy arrays, which leads to the estimator being trained and tested on the same data. 

## How to Reproduce
Simply investigate the source code for the function `_evaluate_performance_regression` within the class `PerformanceEvaluator` in the file `eval_performance.py`. 

## Expected Behavior
The following snippet of code
```
 X_train = np.asarray(X_test)
 X_test = np.asarray(X_test)
 y_train = np.asarray(y_test)
 y_test = np.asarray(y_test)
```
should be changed to: 
```
 X_train = np.asarray(X_train)
 X_test = np.asarray(X_test)
 y_train = np.asarray(y_train)
 y_test = np.asarray(y_test)
```

**Comment by robsdavis** [comment]
@prabaey, thanks for posting this issue! It does indeed seem to be a mistake. A PR to fix this will be created shortly.
