### ISSUE TITLE
Increase upper bound on numpy version

### ISSUE THREAD

**Issue by HLasse** [vanderschaarlab/synthcity#245]
## Question
Hi, thanks again for an excellent package.

Is it possible to upgrade the upper bound of the numpy version to e.g. 1.26.0?

https://github.com/vanderschaarlab/synthcity/blob/ab47bcf38cf7edec946fc630185850dc6eceb5fa/setup.cfg#L39

At the moment this is blocking the package from being installed together with many others with pip.

**Comment by impaktor** [comment]
This can be closed. Fixed in PR above.
