### ISSUE TITLE
Does this library generate synthetic EEG signals, MRI images?

### ISSUE THREAD

**Issue by loukasilias** [vanderschaarlab/synthcity#246]
Hello,

Thank you for this library with so many capabilities.
I would like to ask if I could use this library for generating synthetic EEG signals and MRI images.

Thank you again.
Loukas

**Comment by robsdavis** [comment]
Hi Loukas,

Synthcity allows image generation using the ImageDataLoader object to load you real images and then a synthetic generator model like image_cgan, or image_adsgan. I have not seen it done with MRI images, but there is no reason why not!

If your EEG signals are recorded as time_series data then this is also possible. I'd recommend looking at the tutorials for time series in this case - there are lots of examples there.

Let me know if you need any more info!
