### ISSUE TITLE
Incompatibility between SynthCity and scikit_learn 1.4. With workaround and possible fix

### ISSUE THREAD

**Issue by MarkJacksonRG** [vanderschaarlab/synthcity#249]
## Description
I think there's an incompatibility between `synthcity` and the new 1.4 version of `scikit_learn`? 

## How to Reproduce
I tried running the 'load and run a tabular generator' bit [from the docs](https://synthcity.readthedocs.io/en/latest/#generic-data) and got an error. 
`OneHotEncoder.__init__() got an unexpected keyword 'sparse'` 

<details>
<summary>Click to view screenshot of code and error:</summary> 

![image](https://github.com/vanderschaarlab/synthcity/assets/124061439/56fcccf0-13bf-4c08-b213-8431752e5559)
</details>

## Expected Behavior
It should fit the model without an error

## Workaround
The [OneHotEncoder docs say](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html) `sparse` was renamed to `sparse_output`. The new parameter was introduced in `scikit_learn` 1.2 and the old one removed in `scikit_learn` 1.4.

I fixed my local installation by downgrading scikit_learn to 1.3.2. 
`pip install --upgrade scikit_learn==1.3.2`

## Possible fix
I checked the stack trace and I think it might be possible to fix it with a one-line change. I haven't actually tried it! I'm not setup as a contributor.

Change `sparse` to `sparse_output` in [line 63](https://github.com/vanderschaarlab/synthcity/blob/73cfd8ca784f70141fc7f2969221cd3b5737f7b1/src/synthcity/plugins/core/models/tabular_encoder.py#L63) in `tabular_encoder.py`  : I.e. this line

`cat_encoder_params: dict = dict(handle_unknown="ignore", sparse=False)`

I thought I would flag it here in case it's something the community want to fix. I think you'd need to require scikit_learn 1.2 and greater.

## System Information
 - OS: Windows 10
 - Python 3.10

**Comment by robsdavis** [comment]
Hi [MarkJacksonRG](https://github.com/MarkJacksonRG), Many thanks for your issue! This has now been resolved in the manner you described. This can been seen in #253. If you should ever want to contribute in the future it is very easy (see [CONTRIBUTING.MD](https://github.com/vanderschaarlab/synthcity/blob/main/CONTRIBUTING.MD))!
