### ISSUE TITLE
GOGGLE doesn't exist

### ISSUE THREAD

**Issue by Aduboahen** [vanderschaarlab/synthcity#272]
## Description
Installed synthcity with  `pip install "synthcity[all]"` when I run  `Plugin().get("goggle") `  I get 

> Plugin goggle doesn't exist.

The GOGGLE plugin is also not in the output of `Plugins().list()`

## System Information
 - OS: Ubuntu
 - OS Version: 22.04
 - Language Version: Python 3.10.12

**Comment by robsdavis** [comment]
Hi @Aduboahen, Hmm, that is interesting. The tests passed for google on the main branch yesterday and at the last release. What happens if you `pip install synthcity[goggle]`?

**Comment by Aduboahen** [comment]
Installs without error (all requirements satisfied)

> synthcity[goggle]) (0.16.0)

**Comment by robsdavis** [comment]
Ah, that's it. The error is due to your version of synthcity. Goggle was added in v0.2.5, so v0.16.0 does not contain the plugin. If you want to use goggle, you will need to update your version of synthcity to v0.2.5 or later. This can be done with something like:
`pip install --upgrade synthcity[all]`

I will close this issue now, but please reply if your issue is not resolved and I will reopen it.

**Comment by Aduboahen** [comment]
synthcity is up to date v0.2.10

**Comment by robsdavis** [comment]
Can I cask what does the following command return?
`pip freeze | grep -e dgl -e torch-geometric -e torch-sparse -e torch-scatter`

**Comment by Aduboahen** [comment]
> dgl==2.1.0
> torch-scatter==2.1.2
> torch-sparse==0.6.18

**Comment by robsdavis** [comment]
no result for `torch-geometric`? If not, try `pip install torch-geometric` and then re-try

**Comment by Aduboahen** [comment]
`pip install torch-geometric ` finishes with all Requirements satisfied but `pip freeze | grep torch-geometric` returns empty

**Comment by robsdavis** [comment]
That is odd that it isn't returned by the pip freeze. Could you double check it is installed with: `python -c "import torch_geometric; print(torch_geometric.__version__)"`

**Comment by Aduboahen** [comment]
Yeah it's installed, Returns '2.5.0'

**Comment by robsdavis** [comment]
OK, think I have found the potential issue. Can you try this:
`pip uninstall dgl`
`pip install  dgl==2.0.0 -f https://data.dgl.ai/wheels/repo.html`
Then try again?

I think it could be an issue with dgl support for pytorch 1.13.1.
