### ISSUE TITLE
Fitting terminates at around 10%

### ISSUE THREAD

**Issue by ianlokh** [vanderschaarlab/synthcity#279]
## Description
I am able to run tutorial 0 example. However the training terminates before training is completed at around 10%

## How to Reproduce
1. Go to Tutorial 0
2. Run fit for AdsGAN plugin

## Expected Behavior
I expect the training to run until 10000 as per progress bar

## Screenshots
<img width="1193" alt="Screenshot 2024-06-23 at 17 06 32" src="https://github.com/vanderschaarlab/synthcity/assets/116181/afc004ae-0faf-49fa-8bf8-321eefc2ea45">

## System Information
 - OS: Mac OS (Apple M3)
 - OS Version: 14.5
 - Language Version: Python 3.10
 - Package Manager Version: Conda
 - Browser (if applicable): Safari
 - Browser Version (if applicable): [e.g. 81.0.4044.138]

**Comment by robsdavis** [comment]
Hi @ianlokh,

Thanks for your questions. This is expected behaviour and it due to early stopping. If you wish to force the model to train for longer you can pass a value for `n_iter_min` which means that early stopping will only kick in after `n_iter_min` training iterations.
