### ISSUE TITLE
Add argument n_folds in Benchmark.evaluate() function

### ISSUE THREAD

**Issue by HeidelindeDehaene** [vanderschaarlab/synthcity#280]
When using the Benchmark.evaluate() function, it is possible to specify arguments. 
I was wondering if it would be possible to add there the argument n_folds that is used further down the line in MetricEvaluator? 
Perhaps this is already possible, but I was not able to find information regarding this matter. 

If I understood it correctly, this specifies the KFolds that are used in the eval_performance.py functions. 
It is now set at 3 as default, but it would be nice if you could specify it yourself (e.g. set it at 5 or 10) in Benchmark.evaluate().

Thank you in advance!
Warmest wishes

**Comment by robsdavis** [comment]
Thanks @HeidelindeDehaene - good idea! I will consider abstracting this parameter out to the benchmarks API in the next release
