### ISSUE TITLE
latest release is broken

### ISSUE THREAD

**Issue by fountaindive** [vanderschaarlab/synthcity#283]
## Description

Installing the latest release produces quite a few errors. Is there any chance you could fix them?

e.g. in `synthcity/plugins/core/models/survival_analysis/metrics.py` I had to update

`from scipy.integrate import trapz` to `from scipy.integrate import trapezoid as trapz`

I also needed to install a specific version of `pydantic`. See this [issue](https://github.com/vanderschaarlab/synthcity/issues/256)

I also needed to edit `synthcity/plugins/core/models/tabular_encoder.py` go to the `OrdinalEncoder` and change `sparse -> sparse_output`

Many thanks!

## How to Reproduce

```
ENV_NAME=py312
conda create -y --name $ENV_NAME python=3.12
conda activate $ENV_NAME
python -m pip install synthcity
```

Then in python try using synthcity

```python
from synthcity.plugins import Plugins
```

with traceback

```
  File "/Users/<USERNAME>/anaconda3/envs/py312/lib/python3.12/site-packages/synthcity/plugins/core/models/survival_analysis/metrics.py", line 8, in <module>
    from scipy.integrate import trapz
ImportError: cannot import name 'trapz' from 'scipy.integrate' (/Users/<USERNAME>/anaconda3/envs/py312/lib/python3.12/site-packages/scipy/integrate/__init__.py)
```

however, after you fix this `trapz` error you also get the OrdinalEncoder error when you try to fit a model

## System Information
 - OS: mac
 - OS Version: 14.6.1
 - Language Version: python 3.12
 - Package Manager Version: conda 24.1.2

**Comment by robsdavis** [comment]
Hi @fountaindive, Unfortunately synthcity does not yet support python 3.12. Please try with python 3.10 to be sure everything works

**Comment by fountaindive** [comment]
Hi @robsdavis thanks for getting back to me!

I tried again using python 3.10 but got the same error

```
ImportError: cannot import name 'trapz' from 'scipy.integrate' (/Users/<USERNAME>/anaconda3/envs/py310/lib/python3.10/site-packages/scipy/integrate/__init__.py)
```
