### ISSUE TITLE
Incorrect documentation for TVAE

### ISSUE THREAD

**Issue by dliustats** [vanderschaarlab/synthcity#285]
## Where?
In the documentation, the reference cited for tvae model is discussing conditional GAN. It is not even talking about variational autoencoders. I think the authors put wrong reference for tvae model in the documentation.

The figure below is a screenshot for the tvae description and related reference, taken from Synthcity documentation: https://github.com/vanderschaarlab/synthcity. 
![1](https://github.com/user-attachments/assets/d20df991-00bb-4e10-9686-66047bdf2f99)

## What?
I would like to know what paper the tvae was built and coded upon, as the tvae is a variation of VAE model. The conditional GAN paper should be replaced with the correct reference that tvae was implemented in Synthcity.

**Comment by robsdavis** [comment]
Hi @dliustats,

I understand your confusion, but the docs are correct. The paper that that we base our tvae is the one linked. If you look at page 2 it says:

```To further challenge CTGAN, we adapt a variational autoencoder (VAE) [15] for mixed-type tabular data generation. We call this TVAE.```

And details of their TVAE model are provided on page 6.

The code link that paper provides is this one: https://github.com/sdv-dev/CTGAN.

Hope that helps!
