### ISSUE TITLE
Are there any examples how to use the evaluation framework from 2102.08921

### ISSUE THREAD

**Issue by fountaindive** [vanderschaarlab/synthcity#287]
## Question

In the paper [How Faithful is your Synthetic Data? Sample-level Metrics for Evaluating and Auditing Generative Models](https://arxiv.org/abs/2102.08921) this group proposed a way to evaluate the performance of synthetic data. I was wondering if there any tutorials available that demonstrate how to use the synthcity code to do this?

I think the loss function defined in equation 8 in the above paper is defined [here](https://github.com/vanderschaarlab/synthcity/blob/943fa280687d236d783e53f40302838f5924f422/src/synthcity/metrics/representations/OneClass.py#L26) right?

Do you also recommend using this triple metric approach (α-Precision, β-Recall, Authenticity) for evaluating the performance of synthetic data 

Cheers!

**Comment by robsdavis** [comment]
Hi @fountaindive,

The source code for that paper is all [here](https://github.com/vanderschaarlab/3S-Testing). If you have any specific questions on the paper, you will probably get the best answer by contacting the authors directly. 

I would definitely recommend using α-Precision, β-Recall, and Authenticity for measuring data fidelity (synthetic data quality). We tend to talk about synthetic data performance as being data utility, if that is what you wish to measure then you should measure performance on a downstream model, instead/as well.

Hope that helps!

**Comment by fountaindive** [comment]
Very helpful, thanks @robsdavis ! (And thanks for updating the package recently!)
