### ISSUE TITLE
Progress bar and logging during training

### ISSUE THREAD

**Issue by ZhaozhiQIAN** [vanderschaarlab/synthcity#69]
The training procedure can take a long time. We should add a progress bar or some logging message during training to inform the user. They can control the verbosity of the message by changing the logging level.

**Comment by dionman** [comment]
`# stdlib
import sys
import warnings

import logging
warnings.filterwarnings("ignore")

# third party
from sklearn.datasets import load_diabetes

# synthcity absolute
from synthcity.plugins import Plugins
from synthcity.plugins.core.dataloader import GenericDataLoader

log_level = logging.getLevelName("DEBUG")
logging.basicConfig(stream=sys.stdout, level=log_level)


X, y = load_diabetes(return_X_y=True, as_frame=True)
X["target"] = y

loader = GenericDataLoader(
    X,
    domain_column="target",
)
# synthcity absolute
from synthcity.plugins import Plugins


# Set up the logger with a file handler
logger = logging.getLogger("synthcity.plugins")
logger.setLevel(logging.INFO)
file_handler = logging.FileHandler("info.log")
file_handler.setLevel(logging.INFO)
logger.addHandler(file_handler)

# Log some messages
logger.debug("This is a debug message")
logger.info("This is an info message")
logger.warning("This is a warning message")

Plugins().list()
# Load and train a generative model
# synthcity absolute
from synthcity.plugins import Plugins

syn_model = Plugins().get("radialgan")
print("starting fit")
syn_model.fit(loader)
`

I can only see the progress bar but not INFO log stream ouput with the script above (adapted from the tutorials notebooks). How can I amend it to see/get written on the file all log messages?
